### ISSUE TITLE
Alignment of configuration parameters

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/UVPlugin-relationalFromCKAN#2]
To be aligned with L-*CKAN DPUs, same configuration parameters shall be used:

| Parameter | Description |
| --- | --- |
| **org.opendatanode.CKAN.secret.token** | Token used to authenticate to CKAN, has to be set in backend.properties |
| **org.opendatanode.CKAN.api.url** | URL where CKAN api is located, has to be set in backend.properties |
| **org.opendatanode.CKAN.http.header.[key]** | Custom HTTP header added to requests on CKAN |

see https://github.com/OpenDataNode/UVPlugin-filesToCKAN for inspiration

Readme.md to be updated accordingly

**Comment by mbl-eea-sk** [comment]
Not sure if #2 is solved correctly because of lack of information concerning business and functional specification.

**Comment by skrchnavy** [comment]
`.project` shall not be in repository
