### ISSUE TITLE
DPU won't load my organization datasets

### ISSUE THREAD

**Issue by mvi-eea-sk** [OpenDataNode/UVPlugin-relationalFromCKAN#8]
DPU won't load private datasets that belong to user organization.

This is caused by change in API call organization_show in CKAN from version 2.2.x to version 2.3 as it no longer returns resources, only datasets.

commit to blame: https://github.com/ckan/ckan/commit/e1051693fb399fee77e4853e689c7de2999ccd47

**Comment by eea03** [comment]
@mvi-eea-sk Is this issue solved and tested (nothing to do anymore?)
Can it be released?
